UniLibrary/Controllers/RoomController.cs
using UniLibrary.Interfaces;
using UniLibrary.Models;
using UniLibrary.Factories;
using UniLibrary.ViewModels;
using System.Data.Common;
using Microsoft.EntityFrameworkCore;

namespace UniLibrary.Controllers
{

    public class RoomsController : Controller
    {

        private readonly IRoomService _roomService;

        public RoomsController(IRoomService roomService)
        {
            _roomService = roomService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Create()
        {
            await Task.CompletedTask;
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoomViewModel model)
        {
            try
            {
                foreach (var item in await _roomService.GetAllRoomsAsync())
                {
                    if (item.Name != model.Name)
                    {
                        Room? room = null;
                        switch (model.Room!.ToString())
                        {
                            case "MeetingRoom":
                                room = RoomConcreteFactory.getRoom(Models.Enums.Rooms.MeetingRoom);
                                break;
                            case "StudyRoom":
                                room = RoomConcreteFactory.getRoom(Models.Enums.Rooms.StudyRoom);
                                break;
                            case "ComputerRoom":
                                room = RoomConcreteFactory.getRoom(Models.Enums.Rooms.ComputerRoom);
                                break;
                            case "ConferenceRoom":
                                room = RoomConcreteFactory.getRoom(Models.Enums.Rooms.ConferenceRoom);
                                break;
                        }
                        room!.Name = model.Name;
                        room.Capacity = model.Capacity;
                        room.Floor = model.Floor;
                        await _roomService.AddAsync(room);
                        return Json(new { success = true, message = "Room Created Succcessfully" });
                    }
                    else
                    {
                        return Json(new { error = true, message = "Room Already Exists!" });
                    }
                }
            }
            catch (DbException)
            {
                return Json(new { error = true, message = "Something Went Wrong!" });
            }
            return Json(new { error = true, message = "An Unexpected Error Occured!" });
        }

        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var room = await _roomService.GetByIDAsync(id);
            return View(room);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var room = await _roomService.GetByIDAsync(id);
            return View(room);
        }

        [HttpPost, Authorize(Policy = "Admin")]
        public async Task<IActionResult> EditRoom(int id, string name, int capacity, int floor)
        {
            Room room = await _roomService.GetByIDAsync(id);
            if (id != room.ID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    room.Name = name;
                    room.Capacity = capacity;
                    room.Floor = floor;
                    await _roomService.UpdateAsync(room);
                    TempData["Success"] = "Room Updated Successfully.";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (await RoomExists(room.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        TempData["Error"] = "An Unexpected Error Occured!";
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        private async Task<bool> RoomExists(int id)
        {
            return await _roomService.GetByIDAsync(id) != null;
        }

        #region API CALLS
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var rooms = await _roomService.GetAllRoomsAsync();
            return Json(new { data = rooms });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            if (id != 0)
            {
                try
                {
                    await _roomService.DeleteAsync(id);
                    return Json(new { success = true, message = "Room Deleted Succcessfully!" });
                }
                catch (DbException)
                {
                    return Json(new { error = true, message = "Something Went Wrong!" });
                }
            }
            return Json(new { error = true, message = "An Unexpected Error Occured." });
        }
        #endregion
    }

}

UniLibrary/Controllers/UserController.cs
using UniLibrary.Interfaces;
using UniLibrary.Models;
using UniLibrary.ViewModels;
using Microsoft.EntityFrameworkCore;
using System.Data.Common;
using System.Security.Claims;
using UniLibrary.Models.Enums;

namespace UniLibrary.Controllers
{
#nullable disable

    public class UsersController : Controller
    {
        public readonly IUserService _userService;
        public readonly ILoanService _loanService;

        public UsersController(IUserService userService, ILoanService loanService)
        {
            _userService = userService;
            _loanService = loanService;
        }

        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Index()
        {
            var users = await _userService.GetAllUsersAsync(orderBy: m => m.OrderBy(m => m.Name), includeProperties: m => m.Loans);
            return View(users);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Create()
        {
            await Task.CompletedTask;
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken, AllowAnonymous]
        public async Task<ActionResult> Create(RegisterViewModel registerViewModel, string status)
        {
            var userInDb = await _userService.GetAllAsync();
            foreach (var item in userInDb)
            {
                if (registerViewModel.StudentID.ToLower().Trim() != item.StudentID.ToLower().Trim() && registerViewModel.Name.ToLower().Trim() != item.Name.ToLower().Trim())
                {
                    try
                    {
                        var userType = UserType.Admin;
                        switch (registerViewModel.UserType)
                        {
                            case "Admin":
                                userType = UserType.Admin;
                                break;
                            case "PostGraduate":
                                userType = UserType.PostGraduate;
                                break;
                            case "UnderGraduate":
                                userType = UserType.UnderGraduate;
                                break;
                        }
                        User user = new()
                        {
                            StudentID = registerViewModel.StudentID,
                            Name = registerViewModel.Name,
                            Password = BCrypt.Net.BCrypt.HashPassword(registerViewModel.Password),
                            Type = userType
                        };
                        await _userService.AddAsync(user);
                        TempData["Success"] = "Member Created Successfully";
                        if (status.Equals("Login"))
                        {
                            await LoginUser(registerViewModel.StudentID, registerViewModel.Password, "");
                            return RedirectToAction("Index", "Home");
                        }
                        return RedirectToAction(nameof(Index));
                    }
                    catch (DbException)
                    {
                        TempData["Error"] = "Something Went Wrong. Try Again Later.";
                        return View();
                    }
                }
                else
                {
                    TempData["Error"] = "Member Already Exists";
                    return View();
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("/login")]
        public async Task<IActionResult> Login()
        {
            await Task.CompletedTask;
            return View();
        }

        [HttpPost]
        [Route("/login")]
        public async Task<IActionResult> LoginUser(string studentID, string password, string returnURL)
        {
            var loginValid = ValidateLogin(studentID, password);
            if (!loginValid.Result)
            {
                TempData["LoginFailed"] = $"The username or password is incorrect";
                return Redirect("/login");
            }
            else
            {
                await SignInUser(studentID);
                if (string.IsNullOrWhiteSpace(returnURL) || !returnURL.StartsWith("/"))
                {
                    TempData["Success"] = $"Login Success";
                    returnURL = "/";
                }
                return this.Redirect(returnURL);
            }
        }

        private async Task<bool> ValidateLogin(string studentID, string password)
        {
            var userInDb = await _userService.GetAllAsync();
            foreach (var item in userInDb)
            {
                if (studentID.ToLower().Trim() == item.StudentID.ToLower().Trim())
                {
                    bool verified = BCrypt.Net.BCrypt.Verify(password, item.Password);
                    return verified;
                }
            }
            return false;
        }

        private async Task SignInUser(string studentID)
        {
            var user = await _userService.GetAllAsync();
            foreach (var item in user)
            {
                if (item.StudentID == studentID)
                {
                    TempData["UserID"] = item.ID;
                    TempData["UserName"] = item.Name;
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name,studentID),
                        new Claim("AllRegisteredUsers","true")
                    };
                    if (item.Type == UserType.Admin)
                        claims.Add(new Claim("Admin", "true"));
                    else if (item.Type == UserType.PostGraduate)
                        claims.Add(new Claim("PostGraduate", "true"));
                    else
                        claims.Add(new Claim("UnderGraduate", "true"));
                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                }
            }
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var user = await _userService.GetUserByIdAsync(id, includeProperties: true);
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(int id, [Bind("ID,StudentID,Name")] User user)
        {
            if (id != user.ID)
            {
                return NotFound();
            }
            try
            {
                await _userService.UpdateAsync(user);
                TempData["Success"] = "User updated Successfully";
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (await UserExists(user.ID))
                {
                    return NotFound();
                }
                else
                {
                    TempData["Error"] = "An Unexpected Error Occured!";
                }
            }
            return View(user);
        }

        public async Task<bool> UserExists(int id)
        {
            return await _userService.GetByIDAsync(id) != null;
        }

        [HttpDelete, Authorize(Policy = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var userInDb = await _userService.GetByIDAsync(id);
            var loanInDb = _loanService.GetLoanOrDefault(filter: b => b.UserID == userInDb.ID);
            if (loanInDb != null)
            {
                return Json(new { error = true, message = "You cannot delete this User as long as it has loans referring to it!" });
            }
            await _userService.DeleteAsync(id);
            return Json(new { success = true, message = "User Deleted Successfully." });
        }

    }
}

UniLibrary/Views/Shared/_Footer.cshtml
<footer class="footer">
    <div class="container-fluid bg-dark">
        <section class="p-3 pt-0">
            <div class="row d-flex align-items-center">
                <div class="col-md-7 col-lg-8 text-center text-md-left">
                    <div class="p-3 text-white">
                        &copy; @DateTime.Now.Year - Schmucksman Library
                    </div>
                </div>
                <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-right">
                    <!-- Facebook -->
                    <a class="btn-link   m-1 text-white" role="button">
                        <em class="bi bi-meta"></em>
                    </a>

                    <!-- Twitter -->
                    <a class="btn-link btn-floating m-1 text-white" role="button">
                        <em class="bi bi-twitter"></em>
                    </a>

                    <!-- Google -->
                    <a class="btn-link btn-floating m-1 text-white" role="button">
                        <em class="bi bi-google"></em>
                    </a>

                    <!-- Instagram -->
                    <a class="btn-link btn-floating m-1 text-white" role="button">
                        <em class="bi bi-instagram"></em>
                    </a>
                    <a class="text-left text-white ml-4" asp-area="" asp-controller="Home"
                        asp-action="Privacy">Privacy</a>
                </div>
            </div>
        </section>
    </div>
</footer>

UniLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Schmucksman Library</title>
    @await Html.PartialAsync("_StylesheetPartial")
</head>

<body>
    @await Html.PartialAsync("_Navbar")
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @await Html.PartialAsync("_Notification")
            @RenderBody()
        </main>
    </div>

    @await Html.PartialAsync("_Footer")
    @await Html.PartialAsync("_ScriptsPartial")
    @RenderSection("Scripts", required: false)
</body>

</html>

UniLibrary/Views/Shared/_Navbar.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Schmucksman Library</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Loans" asp-action="Index">Loans</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Computers" asp-action="Index">Computers</a>
                    </li>
                    @if (User!.Identity!.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Create"
                            asp-route-status="Register">Register</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

UniLibrary/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>

    @*<h2 class="container text-success mx-4">@TempData["Success"]</h2>*@
}

@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]');
    </script>
    @*<h2 class="container text-danger mx-4">@TempData["Error"]</h2>*@
}

UniLibrary/Views/Shared/_ScriptsPartial.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>

UniLibrary/Views/Shared/_StylesheetPartial.cshtml
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
<link rel="stylesheet" href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" />
<link rel="stylesheet" href="~/css/site.css" />